---
title: "MarketAnalysis"
author: "Indhresh Achi"
date: "2025-04-14"
output: word_document
---

```{r}
library(tidyverse)
library(readr)
library(tidyr)
library(ggplot2)

# Importing Dataset

market <- read.csv("/Users/indhreshachi/Desktop/MarketingAnalysis.csv")
str(market)

```


```{r}
# Data Wrangling

names(market)

market <- subset(market, select=-c(id))
head(market)

summary(market)
```


```{r}
summary(market$spending_score)

summary(market$income)

summary(market$last_purchase_amount)
```


```{r}
mean(market$income)

mean(market$spending_score)

mean(market$membership_years)
```


```{r}
mean(market$last_purchase_amount)

sd(market$income)

sd(market$spending_score)

sd(market$purchase_frequency)
```


```{r}
# Data Visualization
```


```{r}
boxplot(market$income, main="Income Statistics", col="Green")
```


```{r}
product_freq = table(market$preferred_category)

barplot(height = product_freq, 
        main="Frequency of Preffered Product Category", 
        xlab="Category", ylab="Frequency", col="Blue")
```


```{r fig.height=7, fig.width=10}
hist(market$age, main="Distribution of Age", xlab="Age",ylab="Frequency", col="Red", labels=TRUE)
```


```{r}
member <-  market
member %>% 
  group_by(preferred_category) %>% 
  mutate(mean_membershipYears = mean(membership_years)) %>% 
  select(preferred_category, mean_membershipYears, gender) %>% 
  ggplot(member, mapping= aes(fill=preferred_category,y=mean_membershipYears, x=preferred_category)) +
    geom_bar(position = 'dodge', stat='identity') +
    ggtitle("Preffered Category Based on membership Years")+
  xlab("Category")+
  ylab("Average Membership Years")
```


```{r}
# Machine Learning

## K-Means Clustering

### Elbow Method

library(purrr)

market$gender <- unclass(factor(market$gender))
market$preferred_category <- unclass(factor(market$preferred_category))
```


```{r}
head(market)
```


```{r}
cluster_df <- market
names(cluster_df)
head(cluster_df)
```


```{r}
set.seed(124)


iss <- function(k) { kmeans(cluster_df, k, 
                            iter.max=100, 
                            nstart=100, 
                            algorithm="Lloyd")$tot.withinss }

k.values <-  1:10

iss_values <- map_dbl(k.values, iss)

plot(k.values, iss_values, type="b", pch=18, frame=TRUE, xlab="Number Of Clusters K", 
     ylab="Total Intra-Clusters Sum Of Squares")
```


```{r}
### Silhouwette Method

library(cluster)
library(gridExtra)
library(grid)

k2 <- kmeans(cluster_df, 2, iter.max=100,nstart=50,algorithm="Lloyd")
s2 <- plot(silhouette(k2$cluster, dist(cluster_df, "euclidean")))


k3 <- kmeans(cluster_df, 3, iter.max=100,nstart=50,algorithm="Lloyd")
s3 <- plot(silhouette(k3$cluster, dist(cluster_df, "euclidean")))

k4 <- kmeans(cluster_df, 4, iter.max=100,nstart=50,algorithm="Lloyd")
s4 <- plot(silhouette(k4$cluster, dist(cluster_df, "euclidean")))

k5 <- kmeans(cluster_df, 5, iter.max=100,nstart=50,algorithm="Lloyd")
s5 <- plot(silhouette(k5$cluster, dist(cluster_df, "euclidean")))

k6 <- kmeans(cluster_df, 6, iter.max=100,nstart=50,algorithm="Lloyd")
s6 <- plot(silhouette(k6$cluster, dist(cluster_df, "euclidean")))

k7 <- kmeans(cluster_df, 7, iter.max=100,nstart=50,algorithm="Lloyd")
s7 <- plot(silhouette(k7$cluster, dist(cluster_df, "euclidean")))

k8 <- kmeans(cluster_df, 8, iter.max=100,nstart=50,algorithm="Lloyd")
s8 <- plot(silhouette(k8$cluster, dist(cluster_df, "euclidean")))

k9 <- kmeans(cluster_df, 9, iter.max=100,nstart=50,algorithm="Lloyd")
s9 <- plot(silhouette(k9$cluster, dist(cluster_df, "euclidean")))

k10 <- kmeans(cluster_df, 10, iter.max=100,nstart=50,algorithm="Lloyd")
s10 <- plot(silhouette(k10$cluster, dist(cluster_df, "euclidean")))
```


```{r}
library(ggplot2)
library(NbClust)
library(factoextra)
library(car)

fviz_nbclust(cluster_df, kmeans, method = "wss")

fviz_nbclust(cluster_df, kmeans, method = "silhouette")
```


```{r}
### Gap Statistic Method


k2 <- kmeans(cluster_df, 2, iter.max=100,nstart=50,algorithm="Lloyd")
s2 <- plot(silhouette(k2$cluster, dist(cluster_df, "euclidean")))

#### Principle Cluster Analysis


cluster_df$gender <-  as.numeric(as.factor(cluster_df$gender))
cluster_df$income<-  as.numeric(as.factor(cluster_df$income))
cluster_df$spending_score <-  as.numeric(as.factor(cluster_df$spending_score))
cluster_df$membership_years <-  as.numeric(as.factor(cluster_df$membership_years))
cluster_df$purchase_frequency <-  as.numeric(as.factor(cluster_df$purchase_frequency))
cluster_df$age <-  as.numeric(as.factor(cluster_df$age))
cluster_df$preferred_category <-  as.numeric(as.factor(cluster_df$membership_years))


pcclust <- prcomp(cluster_df)

summary(pcclust)

pcclust$rotation

set.seed(42)
```


```{r}

glimpse(cluster_df)
```


```{r fig.height=10, fig.width=10}

ggplot(cluster_df, aes(x=spending_score, y=age )) +
  geom_point(stat='identity', aes(color=as.factor(k2$cluster))) +
  scale_color_discrete(name=' ',
                       breaks=c("1","2"),
                       labels=c('Cluster 1', 'Cluster 2')) +
  ggtitle("Segments of Customers", subtitle="Using K-Means Clustering Technique")
```


```{r}
kcols = function(vec){cols=rainbow(length(unique(vec)))
  return (cols[as.numeric(as.factor(vec))])}

digCluster <- k2$cluster; 

dignm <- as.character(digCluster) 

plot(pcclust$x, col=kcols(digCluster), pch=19, xlab="K-Means", ylab="Classes")
legend("bottomleft", unique(dignm), fill=unique(kcols(digCluster)))


```

